
  CREATE TABLE "MYSCHEMA"."INVOICES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "INVOICES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "MYSCHEMA"."INVOICE_DETAILS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"INVOICE_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"AMOUNT" NUMBER(12,2), 
	 CONSTRAINT "INVOICE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "INVOICE_DETAILS_INVOICES_FK" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "MYSCHEMA"."INVOICES" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


insert into invoices (id, name) values (1, 'Customer 1');
insert into invoice_details (invoice_id, id, item_id, amount) values (1, 1, 'ABC', 1.23);
insert into invoice_details (invoice_id, id, item_id, amount) values (1, 2, 'DEF', 4.56);

insert into invoices (id, name) values (2, 'Bad Customer');
insert into invoice_details (invoice_id, id, item_id, amount) values (2, 3, 'GHI', 0.23);

commit;